# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 681cbedece07ed723520bc559b5854ebf78bb01d2ca6d42989a91d9e5223e6e6fa9de6fb36f763f4860cfb948c77ff739113477f187332ac9472ebaa1b0646bb

test:
  secret_key_base: fa85ba4e1fadd55e01f8e40a8f5e371c48d1ae1f7215e1cf11b4d163413ef06bda10267df19dcc5936a791f697b00b0388840b5f695666ff9fcc7e1f144d66e9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
